apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://localhost:9200
    database: "[logs-*]"
    jsonData:
      timeField: "@timestamp"

dashboards:
  - name: Log Overview Dashboard
    path: ./dashboards/log_overview.json

  - name: Error Rate Dashboard
    path: ./dashboards/error_rate_dashboard.json
